# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UrlAnalyzer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11UrlAnalyzer.proto\x12\x0burlanalyzer\"!\n\x12UrlAnalyzerRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"*\n\x13UrlAnalyzerResponse\x12\x13\n\x0bisMalicious\x18\x01 \x01(\x08\x32\x65\n\x12UrlAnalyzerService\x12O\n\x08\x43heckURL\x12\x1f.urlanalyzer.UrlAnalyzerRequest\x1a .urlanalyzer.UrlAnalyzerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UrlAnalyzer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_URLANALYZERREQUEST']._serialized_start=34
  _globals['_URLANALYZERREQUEST']._serialized_end=67
  _globals['_URLANALYZERRESPONSE']._serialized_start=69
  _globals['_URLANALYZERRESPONSE']._serialized_end=111
  _globals['_URLANALYZERSERVICE']._serialized_start=113
  _globals['_URLANALYZERSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
